# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lT72www8IyzrmBNANh0jO_1WDmYlMtNY

#Mounted the drive
"""

# prompt: mount drive

from google.colab import drive
drive.mount('/content/drive')

"""# Istall libraries"""

!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

"""# import libraries"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Load dataset fron train.csv

"""

train= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic/train.csv')

"""# print first five 5 values,

using head function


"""

train.head()

"""# print last 5 values, using tail function

"""

train.tail()

"""# to get to know not nulll values, use info function"""

train.info()

"""# shape funtion tell how many rows and column are"""

train.shape

"""# to Check duplicates, use duplicated function"""

train.duplicated()

"""# remove duplicates, use drop_duplicates(), it will delete duplicates from data"""

train.drop_duplicates()

"""# will confirm whether duplicated data removed by using shape again"""

train.shape

"""# check null values"""

train.isnull().sum()

"""# drop column if required(if there is duplicate data) and save it in new variable



"""

train_cleaned=train.drop('Cabin', axis=1)

"""# check data shape"""

train_cleaned.shape

"""# check again"""

train.shape

"""# check mean etc before cleaning and after cleaning"""

train.describe()

train_cleaned.describe()

"""# dropna() used to delete all null values in the data not a column"""

titanic_cleaned=train_cleaned.dropna()

"""# there were 179 duplicates, 891-712"""

titanic_cleaned.shape

titanic_cleaned.isnull().sum()

titanic_cleaned.describe()

"""# Check columns"""

titanic_cleaned.columns

"""# to check outiers plot the data from now use box plot and describe using sea born library first check columns Sex and age

---
sns for sea born


"""

sns.boxplot(x='Sex', y='Age', data=titanic_cleaned)

"""# check out distribution(of whole data) of data using distribution plot. bellshaped"""

sns.distplot(titanic_cleaned['Age'])

"""# filter out the data act as outliers less than 70 or 68"""

titanic_cleaned=titanic_cleaned[titanic_cleaned['Age']<66]

sns.boxplot(y='Age', data=titanic_cleaned )

"""# plot distributiob plot"""

sns.distplot(titanic_cleaned['Age'])

"""# cleaning data of passengerid and Survived - its extra task, not performed in class"""

sns.boxplot(x='Survived', y='PassengerId', data=titanic_cleaned)

sns.displot(titanic_cleaned['PassengerId'])

"""# Cleaning Tickets

"""

sns.boxplot(x='Ticket', y='Fare', data=titanic_cleaned)

sns.boxplot(titanic_cleaned['Fare'])

titanic_cleaned=titanic_cleaned[titanic_cleaned['Fare']<55]

sns.boxplot(titanic_cleaned['Fare'])

sns.displot(titanic_cleaned['Fare'])

sns.boxplot(x='Embarked', y='Fare', data=titanic_cleaned)

sns.boxplot(x='Embarked', data=titanic_cleaned)

titanic_cleaned=titanic_cleaned[titanic_cleaned['Fare']<35]

sns.boxplot(titanic_cleaned['Embarked'])